### ISSUE TITLE
overwrite outputs or skip existing?

### ISSUE THREAD

**Issue by sgibbes** [wri/gfw-analysis#3]
Should the process skip over existing outputs to avoid re-running entire feature class?

**Comment by sgibbes** [comment]
https://github.com/wri/gfw-analysis/blob/master/forest_loss_analysis_tool_simple.py

**Comment by thomas-maschler** [comment]
Can you include a checkbox in the tool form and leave it to the user to decide whether he/she wants to reuse previous results?

**Comment by sgibbes** [comment]
Great idea! I will work on that

**Comment by sgibbes** [comment]
- need to use arcpy.Exists (not os.path.exists) since it is a feature class

**Comment by sgibbes** [comment]
if tool is re-opened, need to check then uncheck "overwrite existing". weird bug

**Comment by thomas-maschler** [comment]
Set overwrite default value to false.
it is currently None
